# Generated by Django 4.2.9 on 2026-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sector', models.CharField(max_length=100)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15)),
                ('profit_loss_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-current_value'],
            },
        ),
    ]
