# Generated by Django 4.2.9 on 2026-02-26 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('related_symbols', models.JSONField(default=list, help_text='List of stock symbols')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('sentiment_score', models.DecimalField(decimal_places=3, help_text='Score between -1 and 1', max_digits=4)),
                ('impact_score', models.IntegerField(help_text='Impact score 1-100')),
                ('predicted_impact', models.JSONField(default=dict, help_text='Predicted price movements')),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
