# Generated by Django 4.2.9 on 2026-02-27 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('related_stocks', models.CharField(help_text='Comma-separated stock symbols', max_length=500)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.5, help_text='0.0 to 1.0')),
                ('impact_score', models.FloatField(default=50.0, help_text='0 to 100')),
                ('impact_category', models.CharField(choices=[('product', 'Product'), ('earnings', 'Earnings'), ('regulation', 'Regulation'), ('market', 'Market'), ('acquisition', 'Acquisition'), ('other', 'Other')], default='other', max_length=20)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='news.financialnews')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialnews',
            index=models.Index(fields=['-published_at'], name='news_financ_publish_6b3f35_idx'),
        ),
        migrations.AddIndex(
            model_name='financialnews',
            index=models.Index(fields=['sentiment'], name='news_financ_sentime_e12397_idx'),
        ),
        migrations.AddIndex(
            model_name='financialnews',
            index=models.Index(fields=['impact_score'], name='news_financ_impact__2db498_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newsbookmark',
            unique_together={('user', 'news')},
        ),
    ]
