# Generated by Django 4.2.9 on 2026-02-26 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='newsbookmark',
            unique_together={('user', 'article')},
        ),
    ]
